"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),{Engine}=require('../src/engine'),Motor=require('../src/enemy-motor');
function setup(){const g=new Engine();g.enemies=[];g.nextExploration=g.eventAt=1e9;const p=g.addPlayer('p');Object.assign(p,{world:'space',mode:'flight',x:80000,y:80000,angle:0,ki:100,invuln:0});return{g,p};}
function step(g,n=1){for(let i=0;i<n;i++)g.tick();}
test('queued attacks take the latest mouse direction rather than the previous strike angle',()=>{const{g,p}=setup();g.input(p.id,{x:0,y:0,angle:0,manualAim:true});g.act(p.id,'attack');g.act(p.id,'attackStart');step(g);g.input(p.id,{x:0,y:0,angle:Math.PI/2,manualAim:true});step(g,2);assert.ok(p.moveAction);assert.ok(Math.abs(p.moveAction.angle-Math.PI/2)<1e-6);assert.ok(Math.abs(p.angle-Math.PI/2)<1e-6);});
test('manual aim can leave a locked target to strike a second direction',()=>{const{g,p}=setup();const a=g.spawn('space','A','vegeta',p.x+80,p.y,false,{hp:1000,maxHp:1000,stun:999}),b=g.spawn('space','B','vegeta',p.x,p.y+80,false,{hp:1000,maxHp:1000,stun:999});p.targetId=a.id;g.input(p.id,{x:0,y:0,angle:Math.PI/2,manualAim:true});g.act(p.id,'attack');step(g,2);assert.equal(a.hp,1000);assert.ok(b.hp<1000);});
test('repeated clicks sustain ten light attacks per second without idle recovery gaps',()=>{const{g,p}=setup();const starts=[];const begin=g.beginMove.bind(g);g.beginMove=(p,k)=>{const ok=begin(p,k);if(ok)starts.push(g.time);return ok;};for(let i=0;i<30;i++){g.act(p.id,'attack');g.tick();}assert.ok(starts.length>=10&&starts.length<=11);for(let i=1;i<starts.length;i++)assert.ok(starts[i]-starts[i-1]<=.101);assert.ok(p.ki>=67);});
test('zero ki still allows weaker slower basic punches, while ki techniques require energy',()=>{const{g,p}=setup();p.ki=0;const e=g.spawn('space','A','vegeta',p.x+75,p.y,false,{hp:1000,maxHp:1000,stun:999});assert.equal(g.act(p.id,'attack'),true);assert.ok(p.moveAction.exhausted);assert.ok(p.moveAction.end-p.moveAction.start>=.2-1e-6);step(g,3);assert.ok(e.hp<1000&&1000-e.hp<10);step(g,4);assert.equal(g.act(p.id,'blast'),false);assert.equal(g.act(p.id,'attack'),true);assert.ok(p.ki>=0);});
test('ground, strafe, boost and aerial attacks select distinct poses and permit movement',()=>{const poses=new Set();for(const [mode,x,y,boost]of [['ground',0,0,false],['ground',1,0,false],['ground',0,1,false],['flight',1,0,true],['flight',0,0,false]]){const{g,p}=setup();p.mode=mode;g.input(p.id,{x,y,boost,angle:0});g.act(p.id,'attack');poses.add(p.moveAction.motion.pose);const before=p.x+p.y;step(g,2);if(x||y)assert.ok(p.x+p.y!==before);assert.ok(g.snapshot(p.id).self.combatAction.motion.pose);}assert.equal(poses.size,5);});
test('late-game enemies accelerate regardless of rank without speeding up the opening',()=>{const early=Motor.profile({level:1,rank:'regular'}),late=Motor.profile({level:18,rank:'regular'});assert.ok(early.startup>=.2);assert.equal(late.startup,1/30);assert.ok(late.recovery<early.recovery);assert.ok(late.chain>early.chain);assert.ok(late.reaction>=.1&&late.reaction<early.reaction);});
