const test=require('node:test'),assert=require('node:assert/strict');
const {Engine}=require('../src/engine');const C=require('../shared/sandbox');
function setup(){const g=new Engine();g.enemies=[];const p=g.addPlayer('p',{name:'Explorer'});return {g,p};}
function cmd(g,p,data){g.time+=.3;return g.sandboxCommand(p.id,data);}
function finish(g,p){assert.ok(p.sandboxJob);g.time=p.sandboxJob.finish;g.tick();}
test('shared deposits grant resources to one finisher only',()=>{const {g,p}=setup(),q=g.addPlayer('q',{});const n=C.nodes(p.world,p.x,p.y)[0];for(const v of [p,q]){v.x=n.x;v.y=n.y;assert.equal(cmd(g,v,{action:'gather',target:n.id}).ok,true);}g.time=Math.max(p.sandboxJob.finish,q.sandboxJob.finish);g.tick();assert.equal(p.sandbox.inventory[n.kind]+q.sandbox.inventory[n.kind],3);assert.equal(cmd(g,q,{action:'gather',target:n.id}).ok,false);});
test('movement interrupts crafting without consuming ingredients',()=>{const {g,p}=setup();p.sandbox.inventory.herb=3;assert.equal(cmd(g,p,{action:'craft',recipe:'medicine'}).ok,true);g.input('p',{x:1,y:0,angle:0});g.tick();assert.equal(p.sandboxJob,null);assert.equal(p.sandbox.inventory.herb,3);assert.equal(p.sandbox.inventory.medicine,0);});
test('crafting completes once and consumes the exact ingredients',()=>{const {g,p}=setup();p.sandbox.inventory.ore=3;p.sandbox.inventory.crystal=1;assert.equal(cmd(g,p,{action:'craft',recipe:'alloy'}).ok,true);finish(g,p);assert.equal(p.sandbox.inventory.alloy,1);assert.equal(p.sandbox.inventory.ore,0);assert.equal(p.sandbox.inventory.crystal,0);g.tick();assert.equal(p.sandbox.inventory.alloy,1);});
test('consumable cooldown survives profile restoration',()=>{const {g,p}=setup();p.sandbox.inventory.medicine=2;p.hp=1;assert.equal(cmd(g,p,{action:'use',item:'medicine'}).ok,true);const q=g.addPlayer('q',g.profile(p));q.hp=1;assert.equal(cmd(g,q,{action:'use',item:'medicine'}).ok,false);assert.equal(q.sandbox.inventory.medicine,1);assert.equal(q.citizenId,p.citizenId);});
test('one market offer cannot be purchased twice and offline proceeds are durable',()=>{const {g,p}=setup();p.sandbox.inventory.ore=8;assert.equal(cmd(g,p,{action:'sell',item:'ore',qty:4,price:70}).ok,true);const id=g.sandboxWorld().market[0].id,q=g.addPlayer('q',{}),r=g.addPlayer('r',{});q.zenni=r.zenni=100;assert.equal(cmd(g,q,{action:'buy',target:id}).ok,true);assert.equal(cmd(g,r,{action:'buy',target:id}).ok,false);assert.equal(q.zenni,30);assert.equal(r.zenni,100);const restored=new Engine();restored.worldMemory=structuredClone(g.worldMemory);const seller=restored.addPlayer('seller',g.profile(p));assert.equal(cmd(restored,seller,{action:'collectSales'}).ok,true);assert.equal(seller.zenni,70);cmd(restored,seller,{action:'collectSales'});assert.equal(seller.zenni,70);});
test('malformed and remote interactions cannot alter the economy',()=>{const {g,p}=setup();p.sandbox.inventory.ore=8;for(const qty of [-1,1.5,Infinity,NaN,999])assert.equal(cmd(g,p,{action:'sell',item:'ore',qty,price:1}).ok,false);assert.equal(cmd(g,p,{action:'gather',target:'elsewhere'}).ok,false);assert.equal(cmd(g,p,{action:'craft',recipe:'__proto__'}).ok,false);assert.equal(p.sandbox.inventory.ore,8);});
test('capacity failure preserves escrow and buyer currency',()=>{const {g,p}=setup();p.sandbox.inventory.ore=5;cmd(g,p,{action:'sell',item:'ore',qty:5,price:50});const q=g.addPlayer('q',{});q.zenni=100;q.sandbox.inventory.herb=120;assert.equal(cmd(g,q,{action:'buy',target:g.sandboxWorld().market[0].id}).ok,false);assert.equal(q.zenni,100);assert.equal(g.sandboxWorld().market.length,1);});
test('construction ownership prevents dismantling another player structure',()=>{const {g,p}=setup();p.x=2500;p.y=2500;p.sandbox.inventory.camp=1;assert.equal(cmd(g,p,{action:'build',kind:'camp'}).ok,true);finish(g,p);const b=g.sandboxWorld().structures[0];assert.ok(b);const q=g.addPlayer('q',{});q.x=b.x;q.y=b.y;assert.equal(cmd(g,q,{action:'pack',target:b.id}).ok,false);p.x=b.x;p.y=b.y;assert.equal(cmd(g,p,{action:'pack',target:b.id}).ok,true);assert.equal(p.sandbox.inventory.camp,1);assert.equal(g.sandboxWorld().structures.length,0);});
test('survey pays only once per region and saves discoveries',()=>{const {g,p}=setup();cmd(g,p,{action:'survey'});finish(g,p);const xp=p.xp;cmd(g,p,{action:'survey'});finish(g,p);assert.equal(p.xp,xp);assert.equal(p.sandbox.discoveries.length,1);assert.deepEqual(g.addPlayer('q',g.profile(p)).sandbox.discoveries,p.sandbox.discoveries);});
test('account and world checkpoint wins over stale compatibility files',async()=>{const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{Store}=require('../src/store');const dir=await fs.mkdtemp(path.join(os.tmpdir(),'uz-checkpoint-'));try{const a=new Store(dir);await a.init();a.accounts={seller:{zenni:7}};a.worldMemory={sandbox:{market:[],credits:{seller:70}}};await a.flush();await fs.writeFile(path.join(dir,'profiles.json'),'{}');await fs.writeFile(path.join(dir,'world.json'),'{}');const b=new Store(dir);await b.init();await b.loadWorld();assert.deepEqual(b.accounts,a.accounts);assert.deepEqual(b.worldMemory,a.worldMemory);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('creation validates appearance and applies a chosen background only once',()=>{const g=new Engine();g.enemies=[];const p=g.addPlayer('p',{origin:'saiyan',creation:{appearance:{cloth:3,cut:'braid',skin:999,body:'wide'},path:'artisan',background:'apprentice'}});assert.equal(p.appearance.cloth,3);assert.equal(p.appearance.skin,0);assert.equal(p.appearance.body,'balanced');assert.equal(p.sandbox.path,'artisan');assert.equal(p.sandbox.inventory.ore,4);p.sandbox.inventory.ore=0;const q=g.addPlayer('q',g.profile(p));assert.equal(q.sandbox.inventory.ore,0);assert.deepEqual(q.appearance,p.appearance);assert.equal(q.background,'apprentice');});
test('equipment bonuses do not accumulate across repeated profile loads',()=>{const g=new Engine();g.enemies=[];let p=g.addPlayer('p',{creation:{}});const stats={...p.stats},hp=p.maxHp;for(let i=0;i<8;i++){p=g.addPlayer('restore'+i,g.profile(p));assert.deepEqual(p.stats,stats);assert.equal(p.maxHp,hp);}assert.equal(cmd(g,p,{action:'unwear',slot:'hands'}).ok,true);assert.equal(p.stats.force,stats.force-1);assert.equal(cmd(g,p,{action:'wear',item:'gear_070'}).ok,true);assert.equal(p.stats.force,stats.force);assert.equal(p.sandbox.inventory.gear_070,0);});
test('unequipping into a full inventory preserves gear and bonuses',()=>{const g=new Engine(),p=g.addPlayer('p',{creation:{}});for(const key of Object.keys(p.sandbox.inventory))p.sandbox.inventory[key]=0;p.sandbox.inventory.ore=120;const stats={...p.stats};assert.equal(cmd(g,p,{action:'unwear',slot:'body'}).ok,false);assert.equal(p.sandbox.equipment.body,'gear_014');assert.deepEqual(p.stats,stats);});
test('decorative furniture builds, persists and returns to its owner inventory',()=>{const {g,p}=setup();p.x=p.y=2500;p.sandbox.inventory.decor_000=1;assert.equal(cmd(g,p,{action:'build',kind:'decor_000'}).ok,true);finish(g,p);const b=g.sandboxWorld().structures[0];p.x=b.x;p.y=b.y;assert.equal(cmd(g,p,{action:'structure',target:b.id}).ok,true);assert.equal(cmd(g,p,{action:'pack',target:b.id}).ok,true);assert.equal(p.sandbox.inventory.decor_000,1);});
