(function (root, factory) {
  const value = factory();
  if (typeof module === "object" && module.exports) module.exports = value;
  else root.UZCombat = value;
})(globalThis, () => {
  const moves = {
    jab: {
      name: "Golpe",
      startup: 1 / 30,
      active: 1 / 30,
      recovery: 1 / 30,
      damage: 18,
      ki: 0,
      range: 118,
      step: 18,
      stun: 0.075,
      posture: 12,
    },
    link: {
      name: "Continuação",
      startup: 1 / 30,
      active: 1 / 30,
      recovery: 1 / 30,
      damage: 20,
      ki: 0,
      range: 124,
      step: 20,
      stun: 0.08,
      posture: 14,
    },
    finisher: {
      name: "Lançamento",
      startup: 2 / 30,
      active: 1 / 30,
      recovery: 1 / 30,
      damage: 30,
      ki: 7,
      range: 132,
      step: 26,
      stun: 0.16,
      posture: 22,
      heavy: true,
    },
    heavy: {
      name: "Quebra de guarda",
      startup: 4 / 30,
      active: 2 / 30,
      recovery: 3 / 30,
      damage: 44,
      ki: 18,
      range: 140,
      step: 28,
      stun: 0.24,
      posture: 80,
      heavy: true,
    },
    ki: {
      name: "Disparo",
      startup: 2 / 30,
      active: 1 / 30,
      recovery: 2 / 30,
      damage: 24,
      ki: 10,
      range: 800,
      speed: 820,
      posture: 15,
    },
    charged: {
      name: "Técnica carregada",
      startup: 7 / 30,
      active: 2 / 30,
      recovery: 6 / 30,
      damage: 68,
      ki: 32,
      range: 1100,
      speed: 1080,
      posture: 38,
      heavy: true,
    },
    weave: {
      name: "Ruptura de ki",
      startup: 2 / 30,
      active: 1 / 30,
      recovery: 2 / 30,
      damage: 25,
      ki: 16,
      range: 760,
      speed: 860,
      posture: 38,
    },
  };
  for (const m of Object.values(moves)) Object.freeze(m);
  return Object.freeze({
    version: 4,
    moves: Object.freeze(moves),
    buffer: 0.18,
    comboWindow: 0.7,
    perfectGuard: 0.133,
    guardRetry: 0.6,
    dashCost: 20,
    dashCooldown: 1.05,
    burstCost: 45,
    burstCooldown: 12,
    duelHP: 600,
    roundSeconds: 180,
  });
});
