(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.UZ = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const WORLDS = [
    {
      id: "earth",
      name: "Terra",
      region: "Monte Paozu",
      subtitle: "Onde toda lenda começa",
      color: "#b6d58c",
      water: "#4caca4",
      tree: "#548251",
      seed: 42,
      mentor: "Mestre Kame",
      skin: "roshi",
      enemy: "Soldado Red Ribbon",
      enemySkin: "soldier",
      icon: "地",
    },
    {
      id: "namek",
      name: "Namekusei",
      region: "Vale do Patriarca",
      subtitle: "Sob três sóis",
      color: "#80bda3",
      water: "#427a9b",
      tree: "#527f87",
      seed: 128,
      mentor: "Patriarca",
      skin: "piccolo",
      enemy: "Soldado de Freeza",
      enemySkin: "frieza",
      icon: "緑",
    },
    {
      id: "vegeta",
      name: "Planeta Vegeta",
      region: "Terras dos saiyajins",
      subtitle: "O orgulho de uma raça",
      color: "#cba280",
      water: "#996c62",
      tree: "#906953",
      seed: 240,
      mentor: "Bardock",
      skin: "vegeta",
      enemy: "Guerreiro saiyajin",
      enemySkin: "vegeta",
      icon: "戦",
    },
    {
      id: "future",
      name: "Futuro de Trunks",
      region: "Capital em ruínas",
      subtitle: "Uma esperança resiste",
      color: "#83969d",
      water: "#40566c",
      tree: "#50696a",
      seed: 354,
      mentor: "Trunks",
      skin: "trunks",
      enemy: "Drone Red Ribbon",
      enemySkin: "android",
      icon: "時",
    },
    {
      id: "otherworld",
      name: "Outro Mundo",
      region: "Jardim do Sr. Kaioh",
      subtitle: "Além do Caminho da Serpente",
      color: "#b9abd3",
      water: "#7a81b5",
      tree: "#8575a3",
      seed: 405,
      mentor: "Sr. Kaioh",
      skin: "kai",
      enemy: "Espírito guerreiro",
      enemySkin: "soldier",
      icon: "界",
    },
    {
      id: "demon",
      name: "Reino Demoníaco",
      region: "Terceiro Mundo",
      subtitle: "Magia além dos limites",
      color: "#a696bd",
      water: "#6d659b",
      tree: "#706184",
      seed: 510,
      mentor: "Glorio",
      skin: "glorio",
      enemy: "Guarda de Gomah",
      enemySkin: "demon",
      icon: "魔",
    },
    {
      id: "vampa",
      name: "Vampa",
      region: "Ermos selvagens",
      subtitle: "Instinto de sobrevivência",
      color: "#afa977",
      water: "#777856",
      tree: "#717044",
      seed: 622,
      mentor: "Cheelai",
      skin: "piccolo",
      enemy: "Fera de Vampa",
      enemySkin: "cell",
      icon: "野",
    },
    {
      id: "divine",
      name: "Domínio Divino",
      region: "Planeta de Bills",
      subtitle: "O caminho dos deuses",
      color: "#c3aed1",
      water: "#8079b3",
      tree: "#8d73a1",
      seed: 742,
      mentor: "Whis",
      skin: "whis",
      enemy: "Aspirante divino",
      enemySkin: "beerus",
      icon: "神",
    },
    {
      id: "arena",
      name: "Mundo do Vazio",
      region: "Arena do Poder",
      subtitle: "Um universo em suas mãos",
      color: "#8b959e",
      water: "#34374f",
      tree: "#55626c",
      seed: 892,
      mentor: "Grande Sacerdote",
      skin: "whis",
      enemy: "Guerreiro do torneio",
      enemySkin: "jiren",
      icon: "力",
    },
    {
      id: "yardrat",
      name: "Yardrat",
      region: "Planícies de teletransporte",
      subtitle: "Domine técnicas além da força bruta",
      color: "#a4b887",
      water: "#477c76",
      tree: "#638461",
      seed: 1004,
      mentor: "Mestre Pybara",
      skin: "yardrat",
      enemy: "Guerreiro de Yardrat",
      enemySkin: "yardrat",
      icon: "瞬",
      atlas: { x: 49, y: 25, u: 7 },
    },
    {
      id: "cereal",
      name: "Cereal",
      region: "Ruínas do povo cerealjins",
      subtitle: "Memória, sobrevivência e precisão",
      color: "#b8a37e",
      water: "#54788c",
      tree: "#727555",
      seed: 1118,
      mentor: "Granolah",
      skin: "granolah",
      enemy: "Atirador Heeter",
      enemySkin: "gas",
      icon: "弓",
      atlas: { x: 55, y: 35, u: 7 },
    },
    {
      id: "sadala",
      name: "Sadala",
      region: "Universo 6 · capital saiyajin",
      subtitle: "Outro caminho para o povo saiyajin",
      color: "#b88d6f",
      water: "#536f8c",
      tree: "#7e7158",
      seed: 1222,
      mentor: "Cabba",
      skin: "cabba",
      enemy: "Patrulha de Champa",
      enemySkin: "champa",
      icon: "六",
      atlas: { x: 77, y: 30, u: 6 },
    },
    {
      id: "champa",
      name: "Planeta de Champa",
      region: "Templo do Universo 6",
      subtitle: "O universo espelhado",
      color: "#c4a9c9",
      water: "#6d76a6",
      tree: "#8a719e",
      seed: 1326,
      mentor: "Vados",
      skin: "vados",
      enemy: "Deus da Destruição Champa",
      enemySkin: "champa",
      icon: "六",
      atlas: { x: 81, y: 43, u: 6 },
    },
    {
      id: "tsufuru",
      name: "Planeta Tsufuru",
      region: "Ruínas da antiga civilização",
      subtitle: "Antes da lenda dos saiyajins",
      color: "#9d9d78",
      water: "#426c72",
      tree: "#6c805d",
      seed: 1430,
      mentor: "Patrulha de elite",
      skin: "baby",
      enemy: "Máquina mutante",
      enemySkin: "baby",
      icon: "古",
      atlas: { x: 33, y: 43, u: 7 },
    },
    {
      id: "kanassa",
      name: "Kanassa",
      region: "Costa do oráculo",
      subtitle: "Um presságio antes da destruição",
      color: "#8797a2",
      water: "#4b7291",
      tree: "#667a78",
      seed: 1534,
      mentor: "Guerreiro Kanassano",
      skin: "kanassan",
      enemy: "Invasor de Freeza",
      enemySkin: "soldier",
      icon: "潮",
      atlas: { x: 39, y: 52, u: 7 },
    },
    {
      id: "konatsu",
      name: "Konats",
      region: "Cidade do flautista",
      subtitle: "A canção que sela um demônio",
      color: "#9e847d",
      water: "#476679",
      tree: "#6b715d",
      seed: 1638,
      mentor: "Tapion",
      skin: "tapion",
      enemy: "Sombra de Hirudegarn",
      enemySkin: "hirudegarn",
      icon: "笛",
      atlas: { x: 44, y: 64, u: 7 },
    },
    {
      id: "sacred",
      name: "Mundo Sagrado dos Kaioshins",
      region: "Árvore do Universo",
      subtitle: "O alto mundo dos deuses",
      color: "#b4cba1",
      water: "#59839e",
      tree: "#7b9b66",
      seed: 1742,
      mentor: "Kaioshin",
      skin: "kaioshin",
      enemy: "Aprendiz de Babidi",
      enemySkin: "dabura",
      icon: "界",
      atlas: { x: 59, y: 73, u: 7 },
    },
    {
      id: "zeno",
      name: "Palácio de Zeno",
      region: "Centro do multiverso",
      subtitle: "Onde os doze universos se encontram",
      color: "#a1bfd6",
      water: "#506c9b",
      tree: "#7186aa",
      seed: 1846,
      mentor: "Grande Sacerdote",
      skin: "whis",
      enemy: "Guarda real",
      enemySkin: "jiren",
      icon: "全",
      atlas: { x: 91, y: 62, u: 0 },
    },
    {
      id: "frieza",
      name: "Planeta Freeza 79",
      region: "Entreposto imperial",
      subtitle: "Um posto da antiga força de Freeza",
      color: "#a5a6b9",
      water: "#4d6885",
      tree: "#7b7384",
      seed: 1950,
      mentor: "Comandante da Patrulha",
      skin: "trunks",
      enemy: "Soldado de Freeza",
      enemySkin: "frieza",
      icon: "帝",
      atlas: { x: 28, y: 28, u: 7 },
    },
  ];
  // Personagens nomeados que já aparecem nas crônicas e encontros deste protótipo.
  // O catálogo alimenta a galeria, os retratos e os modelos vetoriais compartilhados.
  const CHARACTERS = [
    ["goku", "Son Goku", "saiyajin"],
    ["vegeta", "Vegeta", "saiyajin"],
    ["gohan", "Son Gohan", "saiyajin"],
    ["goten", "Son Goten", "saiyajin"],
    ["trunks", "Trunks", "saiyajin"],
    ["futuregohan", "Gohan do Futuro", "saiyajin"],
    ["bardock", "Bardock", "saiyajin"],
    ["raditz", "Raditz", "saiyajin"],
    ["nappa", "Nappa", "saiyajin"],
    ["broly", "Broly", "saiyajin"],
    ["pan", "Pan", "saiyajin"],
    ["cabba", "Cabba", "saiyajin"],
    ["caulifla", "Caulifla", "saiyajin"],
    ["kale", "Kale", "saiyajin"],
    ["krillin", "Kuririn", "terráqueo"],
    ["yamcha", "Yamcha", "terráqueo"],
    ["tien", "Tenshinhan", "terráqueo"],
    ["roshi", "Mestre Kame", "terráqueo"],
    ["chiaotzu", "Chaos", "terráqueo"],
    ["yajirobe", "Yajirobe", "terráqueo"],
    ["piccolo", "Piccolo", "namekuseijin"],
    ["dende", "Dende", "namekuseijin"],
    ["nail", "Nail", "namekuseijin"],
    ["kingpiccolo", "Piccolo Daimaoh", "namekuseijin"],
    ["bulma", "Bulma", "terráqueo"],
    ["android16", "Android 16", "androide"],
    ["android17", "Android 17", "androide"],
    ["android18", "Android 18", "androide"],
    ["gero", "Dr. Gero", "androide"],
    ["cell", "Cell", "bio-androide"],
    ["frieza", "Freeza", "arcosiano"],
    ["cooler", "Cooler", "arcosiano"],
    ["kingcold", "Rei Cold", "arcosiano"],
    ["zarbon", "Zarbon", "arcosiano"],
    ["dodoria", "Dodoria", "arcosiano"],
    ["ginyu", "Capitão Ginyu", "força especial"],
    ["buu", "Majin Boo", "majin"],
    ["dabura", "Dabura", "demônio"],
    ["beerus", "Bills", "deus da destruição"],
    ["whis", "Whis", "anjo"],
    ["champa", "Champa", "deus da destruição"],
    ["vados", "Vados", "anjo"],
    ["jiren", "Jiren", "orgulho"],
    ["hit", "Hit", "assassino"],
    ["toppo", "Toppo", "orgulho"],
    ["dyspo", "Dyspo", "orgulho"],
    ["zamasu", "Zamasu", "kaioshin"],
    ["gokuBlack", "Goku Black", "kaioshin"],
    ["janemba", "Janemba", "demônio"],
    ["hirudegarn", "Hirudegarn", "demônio"],
    ["tapion", "Tapion", "herói"],
    ["granolah", "Granolah", "cerealjin"],
    ["gas", "Gas", "heeter"],
    ["moro", "Moro", "feiticeiro"],
    ["baby", "Baby", "tsufurujin"],
    ["omega", "Omega Shenlong", "dragão"],
    ["shugesh", "Shugesh", "saiyajin"],
    ["pilaf", "Pilaf", "terráqueo"],
    ["tao", "Tao Pai Pai", "terráqueo"],
    ["kingkai", "Sr. Kaioh", "kaioshin"],
    ["kaioshin", "Kaioshin", "kaioshin"],
    ["yakon", "Yakon", "demônio"],
    ["spopovich", "Spopovich", "terráqueo"],
    ["pikkon", "Paikuhan", "outro mundo"],
    ["uub", "Uub", "terráqueo"],
    ["videl", "Videl", "terráqueo"],
    ["turtle", "Um mestre tartaruga", "terráqueo"],
    ["yardrat", "Guerreiro de Yardrat", "yardrat"],
    ["kanassan", "Guerreiro Kanassano", "kanassano"],
    ["chichi", "Chi-Chi", "terráqueo"],
    ["oxking", "Rei Cutelo", "terráqueo"],
    ["launch", "Lunch", "terráqueo"],
    ["oolong", "Oolong", "terráqueo"],
    ["puar", "Pual", "terráqueo"],
    ["arale", "Arale", "terráqueo"],
    ["korin", "Karin", "terráqueo"],
    ["popo", "Sr. Popo", "terráqueo"],
    ["shenron", "Shenlong", "dragão"],
    ["porunga", "Porunga", "dragão", "porunga"],
    ["superShenron", "Super Shenlong", "dragão", "superShenron"],
    ["generalBlue", "General Blue", "terráqueo"],
    ["commanderRed", "Comandante Red", "terráqueo"],
    ["tambourine", "Tambourine", "demônio"],
    ["drWheelo", "Dr. Wheelo", "androide"],
    ["garlicJr", "Garlic Jr.", "demônio"],
    ["turles", "Turles", "saiyajin"],
    ["slug", "Lord Slug", "namekuseijin"],
    ["bojack", "Bojack", "pirata espacial"],
    ["recoome", "Recoome", "força especial"],
    ["jeice", "Jeice", "força especial"],
    ["burter", "Burter", "força especial"],
    ["guldo", "Guldo", "força especial"],
    ["android19", "Android 19", "androide"],
    ["android20", "Android 20", "androide"],
    ["cellJr", "Cell Jr.", "bio-androide"],
    ["babidi", "Babidi", "feiticeiro"],
    ["kibito", "Kibito", "kaioshin"],
    ["frost", "Frost", "arcosiano"],
    ["magetta", "Magetta", "androide"],
    ["botamo", "Botamo", "guerreiro"],
    ["kefla", "Kefla", "saiyajin"],
    ["fusedZamasu", "Zamasu Fundido", "kaioshin"],
    ["kunshi", "Kunshi", "orgulho"],
    ["monaito", "Monaito", "cerealjin"],
    ["elec", "Elec", "heeter"],
    ["maki", "Maki", "heeter"],
    ["oil", "Oil", "heeter"],
    ["monaka", "Monaka", "terráqueo"],
    ["panzy", "Panzy", "demônio"],
    ["glorio", "Glorio", "demônio"],
    ["gomah", "Gomah", "demônio"],
    ["degésu", "Degesu", "demônio"],
    ["neva", "Neva", "namekuseijin"],
    ["arinsu", "Dra. Arinsu", "demônio"],
    ["super17", "Super 17", "androide"],
    ["novaShenron", "Nuova Shenlong", "dragão"],
    ["iceShenron", "Eis Shenlong", "dragão"],
    ["rildo", "General Rildo", "androide"],
    ["paragus", "Paragus", "saiyajin"],
    ["gogeta", "Gogeta", "saiyajin"],
    ["vegito", "Vegetto", "saiyajin"],
    ["goku-ssj", "Son Goku · Super Saiyajin", "saiyajin", "goku", "gold"],
    ["goku-blue", "Son Goku · Super Saiyajin Blue", "saiyajin", "goku", "blue"],
    ["goku-ui", "Son Goku · Instinto Superior", "saiyajin", "goku", "silver"],
    [
      "vegeta-blue",
      "Vegeta · Super Saiyajin Blue",
      "saiyajin",
      "vegeta",
      "blue",
    ],
    ["vegeta-evo", "Vegeta · Evolução", "saiyajin", "vegeta", "purple"],
    ["gohan-beast", "Son Gohan · Beast", "saiyajin", "gohan", "violet"],
    ["freeza-gold", "Freeza Dourado", "arcosiano", "golden", "gold"],
    ["freeza-black", "Freeza Negro", "arcosiano", "blackfrieza", "black"],
    ["cell-perfect", "Cell Perfeito", "bio-androide", "cell", "green"],
    ["majin-kid", "Majin Boo · Puro", "majin", "kidbuu"],
    ["broly-legendary", "Broly · Lendário", "saiyajin", "broly", "green"],
    [
      "zamasu-merged",
      "Zamasu Fundido Corrompido",
      "kaioshin",
      "fusedZamasu",
      "violet",
    ],
    ["kefla-ssj", "Kefla · Super Saiyajin", "saiyajin", "kefla", "gold"],
    [
      "gogeta-blue",
      "Gogeta · Super Saiyajin Blue",
      "saiyajin",
      "gogeta",
      "blue",
    ],
    [
      "vegito-blue",
      "Vegetto · Super Saiyajin Blue",
      "saiyajin",
      "vegito",
      "blue",
    ],
  ].map(([id, name, kind, skin = id, form = false]) => ({
    id,
    name,
    kind,
    skin,
    form,
  }));
  const ORIGINS = [
    {
      id: "saiyan",
      name: "Saiyajin",
      style: "Pressão & mobilidade",
      skin: "goku",
      color: "#ed8d47",
      description: "Combos agressivos. Desperte o Super Saiyajin.",
      technique: "Kamehameha",
      form: "Super Saiyajin",
      hp: 360,
      speed: 235,
    },
    {
      id: "earthling",
      name: "Terráqueo",
      style: "Precisão & técnica",
      skin: "krillin",
      color: "#efba69",
      description: "Menor custo de ki. Técnica acima da força.",
      technique: "Kienzan",
      form: "Potencial liberado",
      hp: 340,
      speed: 245,
    },
    {
      id: "namekian",
      name: "Namekuseijin",
      style: "Alcance & resistência",
      skin: "piccolo",
      color: "#94bc77",
      description: "Mais vitalidade. Domine o Makankosappo.",
      technique: "Makankosappo",
      form: "Fusão namekuseijin",
      hp: 430,
      speed: 215,
    },
    {
      id: "majin",
      name: "Majin",
      style: "Controle & recuperação",
      skin: "buu",
      color: "#dc97b5",
      description: "Recuperação acelerada entre confrontos.",
      technique: "Onda Majin",
      form: "Poder Majin",
      hp: 400,
      speed: 225,
    },
  ];
  // Adapted playable encounters, not transcripts or a claim of episode-complete campaigns.
  const arcs = [
    [
      "db",
      "Dragon Ball",
      "#eeb852",
      [
        [
          "O começo da aventura",
          "earth",
          "Pilaf",
          "pilaf",
          "Bulma detectou uma esfera no vale. Procure Kame e impeça Pilaf de levá-la.",
        ],
        [
          "21º Tenkaichi Budokai",
          "earth",
          "Jackie Chun",
          "roshi",
          "O treinamento terminou. Controle a distância e prove sua técnica.",
        ],
        [
          "Exército Red Ribbon",
          "earth",
          "General Blue",
          "soldier",
          "Os soldados ocuparam o vale. Enfrente o comandante da patrulha.",
        ],
        [
          "A vidente e o guerreiro",
          "otherworld",
          "Son Gohan",
          "goku",
          "Uma lembrança espera no Outro Mundo. Lute com serenidade.",
        ],
        [
          "22º Tenkaichi Budokai",
          "earth",
          "Tenshinhan",
          "krillin",
          "Um rival transforma disciplina em poder. Responda no tempo certo.",
        ],
        [
          "O rei dos demônios",
          "earth",
          "Piccolo Daimaoh",
          "piccolo",
          "A Terra enfrenta uma ameaça antiga. Interrompa sua investida.",
        ],
        [
          "23º Tenkaichi Budokai",
          "earth",
          "Piccolo Jr.",
          "piccolo",
          "A rivalidade chega à arena. Vença sem desperdiçar seu ki.",
        ],
      ],
    ],
    [
      "z",
      "Dragon Ball Z",
      "#ec8e62",
      [
        [
          "O irmão das estrelas",
          "earth",
          "Raditz",
          "raditz",
          "Uma nave pousou perto de Paozu. Investigue a chegada do saiyajin.",
        ],
        [
          "A invasão saiyajin",
          "earth",
          "Nappa",
          "vegeta",
          "Proteja a Terra e quebre a ofensiva de Nappa.",
        ],
        [
          "O príncipe dos saiyajins",
          "earth",
          "Vegeta",
          "vegeta",
          "O orgulho encontra a determinação. Sobreviva à pressão do príncipe.",
        ],
        [
          "As forças especiais",
          "namek",
          "Capitão Ginyu",
          "ginyu",
          "Os invasores procuram as esferas. Encontre o capitão.",
        ],
        [
          "O imperador do universo",
          "namek",
          "Freeza",
          "frieza",
          "O destino de Namekusei está em jogo. Vença o imperador.",
        ],
        [
          "A ameaça dos androides",
          "future",
          "Androide 18",
          "android",
          "Trunks pede ajuda. Intercepte os androides entre as ruínas.",
        ],
        [
          "Os Jogos de Cell",
          "future",
          "Cell Perfeito",
          "cell",
          "A perfeição exige uma resposta. Leia os ataques de Cell.",
        ],
        [
          "O despertar de Majin Buu",
          "earth",
          "Majin Buu",
          "buu",
          "A magia de Babidi libertou Buu. Contenha sua energia.",
        ],
        [
          "O último combate",
          "otherworld",
          "Kid Buu",
          "kidbuu",
          "A batalha atravessa mundos. Encontre uma abertura na fúria de Buu.",
        ],
      ],
    ],
    [
      "daima",
      "Dragon Ball DAIMA",
      "#b99bdf",
      [
        [
          "Além do portal",
          "demon",
          "Guarda Real",
          "demon",
          "Entre no Reino Demoníaco e encontre Glorio.",
        ],
        [
          "As esferas demoníacas",
          "demon",
          "Tamagami 3",
          "android",
          "O guardião testa quem merece a esfera. Observe antes de atacar.",
        ],
        [
          "O castelo de Gomah",
          "demon",
          "Gomah",
          "demon",
          "Chegue ao castelo e interrompa os planos do novo rei.",
        ],
      ],
    ],
    [
      "super",
      "Dragon Ball Super",
      "#73bec8",
      [
        [
          "A batalha dos deuses",
          "divine",
          "Bills",
          "beerus",
          "O Deus da Destruição despertou. Treine com Whis antes do duelo.",
        ],
        [
          "O retorno de Freeza",
          "earth",
          "Golden Freeza",
          "golden",
          "Um antigo inimigo retorna. Proteja a Terra novamente.",
        ],
        [
          "Universo 6",
          "arena",
          "Hit",
          "hit",
          "Um assassino domina o tempo. Use esquivas curtas e ataques precisos.",
        ],
        [
          "A justiça de Zamasu",
          "future",
          "Goku Black",
          "black",
          "Uma presença distorce o futuro. Ajude Trunks a resistir.",
        ],
        [
          "O Torneio do Poder",
          "arena",
          "Jiren",
          "jiren",
          "O universo depende de sua equipe. Encare o guerreiro mais forte.",
        ],
        [
          "O saiyajin de Vampa",
          "vampa",
          "Broly",
          "broly",
          "Uma força sem controle surgiu em Vampa. Sobreviva ao encontro.",
        ],
        [
          "Prisioneiro da Patrulha Galáctica",
          "namek",
          "Moro",
          "moro",
          "A energia do planeta desaparece. Detenha o devorador de mundos.",
        ],
        [
          "O sobrevivente",
          "vegeta",
          "Granolah",
          "trunks",
          "Um desejo rompeu o equilíbrio. Enfrente o sobrevivente cerealiano.",
        ],
        [
          "Super Hero",
          "earth",
          "Cell Max",
          "cell",
          "A Red Ribbon retornou. Uma criação colossal ameaça a Terra.",
        ],
      ],
    ],
    [
      "gt",
      "Dragon Ball GT · linha alternativa",
      "#d7a080",
      [
        [
          "Esferas de estrelas negras",
          "vampa",
          "General Rilldo",
          "android",
          "Uma nova viagem começa. Recupere a rota das esferas.",
        ],
        [
          "A vingança de Baby",
          "vegeta",
          "Baby Vegeta",
          "vegeta",
          "O passado dos saiyajins retorna na forma de Baby.",
        ],
        [
          "Super 17",
          "future",
          "Super 17",
          "android",
          "Uma passagem liga dois mundos. Impeça a fusão dos androides.",
        ],
        [
          "Os dragões malignos",
          "earth",
          "Omega Shenlong",
          "omega",
          "O uso das esferas deixou consequências. Restaure o equilíbrio.",
        ],
      ],
    ],
    [
      "movies",
      "Filmes · encontros alternativos",
      "#9eafcb",
      [
        [
          "A zona morta",
          "demon",
          "Garlic Jr.",
          "demon",
          "Um portal ameaça engolir a Terra.",
        ],
        [
          "O mais forte do mundo",
          "future",
          "Dr. Wheelo",
          "android",
          "Uma máquina procura o corpo do guerreiro perfeito.",
        ],
        [
          "A árvore do poder",
          "earth",
          "Turles",
          "goku",
          "Uma árvore está drenando a energia do planeta.",
        ],
        [
          "O falso Super Saiyajin",
          "earth",
          "Lord Slug",
          "piccolo",
          "O invasor namekuseijin chegou à Terra.",
        ],
        [
          "A vingança de Cooler",
          "namek",
          "Cooler",
          "frieza",
          "O irmão de Freeza exige uma revanche.",
        ],
        [
          "O retorno de Cooler",
          "namek",
          "Metal Cooler",
          "android",
          "O Big Gete Star começou a absorver o planeta.",
        ],
        [
          "O androide definitivo",
          "future",
          "Androide 13",
          "android",
          "Um novo androide concluiu sua transformação.",
        ],
        [
          "O lendário Super Saiyajin",
          "vegeta",
          "Broly Lendário",
          "broly",
          "O poder da lenda rompe os limites.",
        ],
        [
          "O guerreiro das galáxias",
          "arena",
          "Bojack",
          "ginyu",
          "Um torneio revelou uma ameaça inesperada.",
        ],
        [
          "O retorno de Broly",
          "earth",
          "Broly Desperto",
          "broly",
          "O saiyajin lendário encontrou a Terra.",
        ],
        [
          "Bio-Broly",
          "future",
          "Bio-Broly",
          "cell",
          "Uma experiência saiu de controle.",
        ],
        [
          "O renascimento da fusão",
          "otherworld",
          "Janemba",
          "demon",
          "O Outro Mundo perdeu seu equilíbrio.",
        ],
        [
          "A ira do dragão",
          "earth",
          "Hirudegarn",
          "omega",
          "A melodia de Tapion anuncia o perigo.",
        ],
      ],
    ],
  ];
  const CAMPAIGNS = arcs.map(([id, name, color, chapters]) => ({
    id,
    name,
    color,
    chapters: chapters.map(([title, world, boss, skin, story], i) => ({
      id: `${id}-${i}`,
      title,
      world,
      boss,
      skin,
      story,
      reward: 160 + i * 35,
      index: i,
    })),
  }));
  function rng(seed) {
    return () => {
      seed |= 0;
      seed = (seed + 0x6d2b79f5) | 0;
      let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
      t ^= t + Math.imul(t ^ (t >>> 7), 61 | t);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  const TECHNIQUES = [
    {
      id: "ki",
      name: "Disparo de ki",
      world: "earth",
      level: 1,
      cost: 0,
      multiplier: 1,
      description: "Disparo rápido. Segure para concentrar.",
    },
    {
      id: "kame",
      name: "Kamehameha",
      world: "earth",
      level: 2,
      cost: 100,
      multiplier: 1.25,
      description: "Feixe concentrado da Escola da Tartaruga.",
    },
    {
      id: "makan",
      name: "Makankosappo",
      world: "namek",
      level: 4,
      cost: 200,
      multiplier: 1.4,
      description: "Perfuração: atravessa alvos mesmo sem carregar.",
    },
    {
      id: "galick",
      name: "Galick Ho",
      world: "vegeta",
      level: 5,
      cost: 260,
      multiplier: 1.55,
      description: "Poder saiyajin. Dano alto, maior custo de ki.",
    },
    {
      id: "genki",
      name: "Genki Dama",
      world: "otherworld",
      level: 8,
      cost: 400,
      multiplier: 2,
      description: "Esfera lenta, ampla e poderosa.",
    },
    {
      id: "divine",
      name: "Ki divino",
      world: "divine",
      level: 12,
      cost: 650,
      multiplier: 1.8,
      description: "Energia refinada. Viaja mais rápido.",
    },
  ];
  TECHNIQUES.push({ id: "teleport", name: "Transmissão instantânea", world: "yardrat", level: 3, cost: 250, multiplier: 1, description: "Aprenda em Yardrat. Viaje a pontos já descobertos por 40 de ki." });
  const SIZE = 3400;
  function getWorld(id) {
    if (id === "space") return { ...WORLDS[0], id, name: "Espaço profundo", region: "Rotas estelares", subtitle: "Voo interestelar", color: "#68caff", seed: 42, mentor: "Navegação" };
    const fixed = WORLDS.find((w) => w.id === id);
    if (fixed) return fixed;
    if (typeof id === "string" && /^rift:[0-9]{1,18}$/.test(id)) {
      const n = BigInt(id.slice(5));
      const base = WORLDS[Number(n % BigInt(WORLDS.length))];
      return {
        ...base,
        id,
        name: `Fronteira ${n}`,
        region: "Expedição procedural",
        subtitle: "Além dos mapas conhecidos",
        seed: Number(n % 2147483647n) + 1000,
        mentor: "Patrulheiro galáctico",
        skin: "trunks",
        procedural: true,
      };
    }
    return WORLDS[0];
  }
  function worldData(id) {
    const world = getWorld(id),
      random = rng(world.seed);
    const objects = [];
    for (let i = 0; i < 320; i++) {
      const x = 100 + random() * 3200,
        y = 100 + random() * 3200;
      // Keep the village, roads, spawn, mentor, and battle clearing readable.
      if (
        Math.hypot(x - 1700, y - 1700) < 340 ||
        Math.hypot(x - 2260, y - 1330) < 320 ||
        Math.abs(y - (1810 + Math.sin(x / 480) * 65)) < 95 ||
        Math.abs(x - 1640) < 80
      )
        continue;
      objects.push({
        x: Math.round(x),
        y: Math.round(y),
        type: random() > 0.27 ? "tree" : "rock",
        size: 26 + random() * 33,
      });
    }
    const buildings = [
      { x: 1430, y: 1510, type: "house", label: "DOJO KAME" },
      { x: 1830, y: 1470, type: "capsule", label: "CAPSULE CORP." },
      { x: 1420, y: 1990, type: "house", label: "POUSADA" },
      { x: 1880, y: 1980, type: "dome", label: "PATRULHA" },
    ];
    if (id !== "earth") {
      const labels = id === "namek" ? ["ALDEIA NAMEKUSEIJIN", "CÚPULA DO ANCIÃO", "ABRIGO", "PATRULHA"] :
        id === "yardrat" ? ["DOJO DE YARDRAT", "SANTUÁRIO", "REFÚGIO", "PATRULHA"] :
        id === "vegeta" ? ["BASE SAIYAJIN", "CENTRO DE COMANDO", "QUARTÉIS", "CÁPSULA DE TREINO"] :
        ["SANTUÁRIO", "POSTO AVANÇADO", "REFÚGIO", "PATRULHA"];
      buildings.forEach((b, i) => { b.label = labels[i]; });
    }
    return {
      world,
      objects,
      buildings,
      spawn: { x: 1700, y: 1740 },
      mentor: { x: 1540, y: 1640 },
      arena: { x: 2260, y: 1330 },
      orbs: Array.from({ length: 7 }, (_, i) => ({
        id: i + 1,
        x: 1700 + Math.cos((i * Math.PI * 2) / 7) * 1050,
        y: 1700 + Math.sin((i * Math.PI * 2) / 7) * 1050,
      })),
    };
  }
  const ACTIONS = {
    attack: { name: "Golpe", key: "J", cost: 0, cooldown: 0.24 },
    blast: { name: "Técnica", key: "K", cost: 22, cooldown: 0.65 },
    dash: { name: "Esquiva", key: "Espaço", cost: 14, cooldown: 0.75 },
    guard: { name: "Defesa", key: "L", cost: 0, cooldown: 0 },
  };
  return {
    WORLDS,
    CHARACTERS,
    ORIGINS,
    CAMPAIGNS,
    TECHNIQUES,
    SIZE,
    worldData,
    getWorld,
    rng,
    ACTIONS,
  };
});
