(function(root,factory){
  if(typeof module==='object'&&module.exports)module.exports=factory();
  else root.UZQuests=factory();
})(typeof globalThis!=='undefined'?globalThis:this,function(){
"use strict";

// Campanha data only: these coordinates are logical story landmarks and do
// not create or change any map art.
const SAGAS = Object.freeze({
  androids:{id:'androids',title:'A sombra dos androides',firstQuest:'android-warning'},
  buu:{id:'buu',title:'O despertar de Majin Buu',firstQuest:'buu-signal'},
  "dragon-ball": { id: "dragon-ball", title: "Aventura da Terra", firstQuest: "db-paozu" },
  saiyan: { id: "saiyan", title: "Invasão Saiyajin", firstQuest: "saiyan-raditz" },
  namek: { id: "namek", title: "Conflito em Namekusei", firstQuest: "namek-arrival" },
});

const LANDMARKS = Object.freeze({
  capsuleLab:{id:'capsuleLab',world:'earth',region:'Cidade do Oeste',x:10040,y:3200,radius:160},
  androidTown:{id:'androidTown',world:'earth',region:'Cidade do Oeste',x:11300,y:2800,radius:260},
  cellArena:{id:'cellArena',world:'earth',region:'Terras do torneio',x:14900,y:14200,radius:300},
  babidiShip:{id:'babidiShip',world:'earth',region:'Deserto de Yamcha',x:-8100,y:6900,radius:260},
  buuWastes:{id:'buuWastes',world:'sacred',region:'Mundo dos Kaioshins',x:2900,y:2700,radius:330},
  paozu: { id: "paozu", world: "earth", region: "Montanhas Paozu", x: 1700, y: 1740, radius: 300 },
  bulma: { id: "bulma", world: "earth", region: "Montanhas Paozu", x: 1700, y: 8250, radius: 115 },
  pilafTrail: { id: "pilafTrail", world: "earth", region: "Cidade do Oeste", x: 9600, y: 3100, radius: 220 },
  pilafHideout: { id: "pilafHideout", world: "earth", region: "Cidade do Oeste", x: 10100, y: 3650, radius: 260 },
  kameHouse: { id: "kameHouse", world: "earth", region: "Kame House", x: 3200, y: 4200, radius: 190 },
  tournament: { id: "tournament", world: "earth", region: "Terras do torneio", x: 14200, y: 13500, radius: 260 },
  ribbonFront: { id: "ribbonFront", world: "earth", region: "Território da Red Ribbon", x: 6200, y: -9800, radius: 240 },
  ribbonCamp: { id: "ribbonCamp", world: "earth", region: "Território da Red Ribbon", x: 7100, y: -10400, radius: 240 },
  ribbonBase: { id: "ribbonBase", world: "earth", region: "Território da Red Ribbon", x: 8600, y: -11600, radius: 290 },
  yamchaDesert: { id: "yamchaDesert", world: "earth", region: "Deserto de Yamcha", x: -7200, y: 6300, radius: 270 },
  babaArena: { id: "babaArena", world: "earth", region: "Deserto de Yamcha", x: -6500, y: 7100, radius: 180 },
  demonCity: { id: "demonCity", world: "earth", region: "Cidade do Oeste", x: 10800, y: 4200, radius: 250 },
  piccoloKeep: { id: "piccoloKeep", world: "earth", region: "Cidade do Oeste", x: 12100, y: 5100, radius: 270 },
  raditzCrater: { id: "raditzCrater", world: "earth", region: "Montanhas Paozu", x: 3800, y: -3900, radius: 220 },
  saiyanBattlefield: { id: "saiyanBattlefield", world: "earth", region: "Montanhas Paozu", x: 4800, y: -2500, radius: 310 },
  snakeEntry: { id: "snakeEntry", world: "otherworld", region: "Caminho da Serpente", x: 1700, y: 1740, radius: 210 },
  bubbles: { id: "bubbles", world: "otherworld", region: "Planeta do Senhor Kaio", x: 16000, y: 1740, radius: 200 },
  namekLanding: { id: "namekLanding", world: "namek", region: "Vale do Patriarca", x: 1700, y: 1740, radius: 300 },
  namekVillage: { id: "namekVillage", world: "namek", region: "Vale do Patriarca", x: 1540, y: 1640, radius: 220 },
  namekRidge: { id: "namekRidge", world: "namek", region: "Vale do Patriarca", x: 5200, y: 3800, radius: 280 },
  namekCamp: { id: "namekCamp", world: "namek", region: "Vale do Patriarca", x: -6100, y: 5900, radius: 270 },
  namekElder: { id: "namekElder", world: "namek", region: "Vale do Patriarca", x: 7600, y: -5100, radius: 220 },
  ginyuField: { id: "ginyuField", world: "namek", region: "Vale do Patriarca", x: 9800, y: 7400, radius: 300 },
  friezaShip: { id: "friezaShip", world: "namek", region: "Vale do Patriarca", x: -10400, y: 2600, radius: 310 },
  namekFinal: { id: "namekFinal", world: "namek", region: "Vale do Patriarca", x: 14200, y: -11200, radius: 300 },
  namekEscape: { id: "namekEscape", world: "namek", region: "Vale do Patriarca", x: 1700, y: 1740, radius: 230 },
  pilafNote1: { id: "pilafNote1", world: "earth", region: "Cidade do Oeste", x: 9850, y: 3350, radius: 105, item: "pilafIntel" },
  rrIntel1: { id: "rrIntel1", world: "earth", region: "Território da Red Ribbon", x: 6700, y: -9400, radius: 110, item: "redRibbonIntel" },
  rrIntel2: { id: "rrIntel2", world: "earth", region: "Território da Red Ribbon", x: 7350, y: -10100, radius: 110, item: "redRibbonIntel" },
  rrIntel3: { id: "rrIntel3", world: "earth", region: "Território da Red Ribbon", x: 7900, y: -10800, radius: 110, item: "redRibbonIntel" },
  namekBall1: { id: "namekBall1", world: "namek", region: "Vale do Patriarca", x: 3200, y: 4200, radius: 110, item: "namekDragonBall" },
  namekBall2: { id: "namekBall2", world: "namek", region: "Vale do Patriarca", x: -7200, y: 6300, radius: 110, item: "namekDragonBall" },
  namekBall3: { id: "namekBall3", world: "namek", region: "Vale do Patriarca", x: 6200, y: -9800, radius: 110, item: "namekDragonBall" },
  namekBall4: { id: "namekBall4", world: "namek", region: "Vale do Patriarca", x: -12000, y: -6200, radius: 110, item: "namekDragonBall" },
  namekBall5: { id: "namekBall5", world: "namek", region: "Vale do Patriarca", x: 14200, y: 13500, radius: 110, item: "namekDragonBall" },
  namekBall6: { id: "namekBall6", world: "namek", region: "Vale do Patriarca", x: 8500, y: 9500, radius: 110, item: "namekDragonBall" },
  namekBall7: { id: "namekBall7", world: "namek", region: "Vale do Patriarca", x: -9300, y: -11900, radius: 110, item: "namekDragonBall" },
});

const ENEMY_PROFILES = Object.freeze({
  aggressive: { archetype: "aggressive", moveSpeed: 1.12, meleeRange: 190, attackCooldown: 1.0, windup: 0.34, damageMultiplier: 1.08, pattern: "cone", guardInterval: 0 },
  tank: { archetype: "tank", moveSpeed: 0.68, meleeRange: 205, attackCooldown: 1.75, windup: 0.7, damageMultiplier: 1.35, pattern: "ring", guardInterval: 4.2, guardDuration: 0.55 },
  speedster: { archetype: "speedster", moveSpeed: 1.65, meleeRange: 155, attackCooldown: 0.8, windup: 0.27, damageMultiplier: 0.88, pattern: "cone", guardInterval: 0 },
  zoner: { archetype: "zoner", moveSpeed: 0.9, meleeRange: 130, rangedRange: 900, attackCooldown: 1.25, windup: 0.56, damageMultiplier: 1, pattern: "beam", guardInterval: 5.5, guardDuration: 0.45 },
  technical: { archetype: "technical", moveSpeed: 1.08, meleeRange: 175, rangedRange: 650, attackCooldown: 1.15, windup: 0.44, damageMultiplier: 0.96, pattern: "cone", guardInterval: 3.6, guardDuration: 0.48 },
  balanced: { archetype: "balanced", moveSpeed: 1, meleeRange: 180, rangedRange: 760, attackCooldown: 1.3, windup: 0.48, damageMultiplier: 1, pattern: "cone", guardInterval: 4.8, guardDuration: 0.5 },
  ranged: { archetype: "ranged", moveSpeed: 0.88, meleeRange: 145, rangedRange: 980, attackCooldown: 1.35, windup: 0.6, damageMultiplier: 1.05, pattern: "beam", guardInterval: 5.8, guardDuration: 0.45 },
});

const BOSSES = Object.freeze({
  cell:{id:'cell',name:'Cell',skin:'cell',hp:2400,damage:40,profile:'technical',phases:[{name:'Forma perfeita',hpThreshold:1,profile:'technical'},{name:'Pressão perfeita',hpThreshold:.6,profile:'ranged'},{name:'Tudo ou nada',hpThreshold:.25,profile:'aggressive'}]},
  dabura:{id:'dabura',name:'Dabura',skin:'dabura',hp:1900,damage:42,profile:'technical',phases:[{name:'Guardião da nave',hpThreshold:1,profile:'technical'},{name:'Fúria demoníaca',hpThreshold:.45,profile:'ranged'}]},
  kidBuu:{id:'kidBuu',name:'Majin Buu',skin:'buu',hp:3100,damage:44,profile:'aggressive',phases:[{name:'Poder sem freios',hpThreshold:1,profile:'aggressive'},{name:'Tempestade de ki',hpThreshold:.65,profile:'ranged'},{name:'Última resistência',hpThreshold:.3,profile:'speedster'}]},
  pilaf: { id: "pilaf", name: "Pilaf", skin: "pilaf", hp: 430, damage: 19, profile: "zoner", phases: [{ name: "Autômato de Pilaf", hpThreshold: 1, profile: "zoner" }, { name: "Sobrecarga do autômato", hpThreshold: 0.42, profile: "aggressive" }] },
  jackieChun: { id: "jackieChun", name: "Jackie Chun", skin: "roshi", hp: 520, damage: 21, profile: "technical", phases: [{ name: "Leitura de combate", hpThreshold: 1, profile: "technical" }] },
  generalBlue: { id: "generalBlue", name: "General Blue", skin: "generalBlue", hp: 560, damage: 22, profile: "technical", phases: [{ name: "Precisão psíquica", hpThreshold: 1, profile: "technical" }, { name: "Pressão de curta distância", hpThreshold: 0.42, profile: "aggressive" }] },
  commanderRed: { id: "commanderRed", name: "Comandante Red", skin: "commanderRed", hp: 600, damage: 22, profile: "ranged", phases: [{ name: "Defesa do comando", hpThreshold: 1, profile: "ranged" }] },
  grandpaGohan: { id: "grandpaGohan", name: "Desafio de Gohan Ancião", skin: "gohan", hp: 460, damage: 19, profile: "technical", phases: [{ name: "Prova de técnica", hpThreshold: 1, profile: "technical" }] },
  tenshinhan: { id: "tenshinhan", name: "Tenshinhan", skin: "tien", hp: 630, damage: 24, profile: "technical", phases: [{ name: "Ritmo calculado", hpThreshold: 1, profile: "technical" }, { name: "Pressão crescente", hpThreshold: 0.42, profile: "speedster" }] },
  tambourine: { id: "tambourine", name: "Tambourine", skin: "tambourine", hp: 480, damage: 23, profile: "speedster", phases: [{ name: "Caçada demoníaca", hpThreshold: 1, profile: "speedster" }] },
  kingPiccolo: { id: "kingPiccolo", name: "Piccolo Daimaoh", skin: "kingpiccolo", hp: 880, damage: 29, profile: "ranged", phases: [{ name: "Ki demoníaco", hpThreshold: 1, profile: "ranged" }, { name: "Fúria do Daimaoh", hpThreshold: 0.38, profile: "aggressive" }] },
  piccoloJr: { id: "piccoloJr", name: "Piccolo Jr.", skin: "piccolo", hp: 820, damage: 27, profile: "balanced", phases: [{ name: "Controle de arena", hpThreshold: 1, profile: "balanced" }, { name: "Pressão final", hpThreshold: 0.4, profile: "aggressive" }] },
  raditz: { id: "raditz", name: "Raditz", skin: "raditz", hp: 680, damage: 27, profile: "speedster", phases: [{ name: "Assalto à distância", hpThreshold: 1, profile: "ranged" }, { name: "Combate corpo a corpo", hpThreshold: 0.5, profile: "aggressive" }] },
  nappa: { id: "nappa", name: "Nappa", skin: "nappa", hp: 920, damage: 32, profile: "tank", phases: [{ name: "Avanço implacável", hpThreshold: 1, profile: "tank" }] },
  vegeta: { id: "vegeta", name: "Vegeta", skin: "vegeta", hp: 1250, damage: 34, profile: "balanced", phases: [{ name: "Confronto calculado", hpThreshold: 1, profile: "balanced" }, { name: "Agressividade saiyajin", hpThreshold: 0.62, profile: "aggressive" }, { name: "Última ofensiva", hpThreshold: 0.28, profile: "speedster" }] },
  dodoria: { id: "dodoria", name: "Dodoria", skin: "dodoria", hp: 820, damage: 30, profile: "tank", phases: [{ name: "Perseguição brutal", hpThreshold: 1, profile: "tank" }] },
  zarbon: { id: "zarbon", name: "Zarbon", skin: "zarbon", hp: 900, damage: 29, profile: "technical", phases: [{ name: "Zarbon", hpThreshold: 1, profile: "technical" }, { name: "Poder liberado", hpThreshold: 0.48, profile: "aggressive" }] },
  guldo: { id: "guldo", name: "Guldo", skin: "guldo", hp: 570, damage: 24, profile: "technical", phases: [{ name: "Ataques oportunistas", hpThreshold: 1, profile: "technical" }] },
  recoome: { id: "recoome", name: "Recoome", skin: "recoome", hp: 940, damage: 34, profile: "tank", phases: [{ name: "Pressão pesada", hpThreshold: 1, profile: "tank" }] },
  burter: { id: "burter", name: "Burter", skin: "burter", hp: 710, damage: 27, profile: "speedster", phases: [{ name: "Velocidade máxima", hpThreshold: 1, profile: "speedster" }] },
  jeice: { id: "jeice", name: "Jeice", skin: "jeice", hp: 730, damage: 27, profile: "ranged", phases: [{ name: "Combate à distância", hpThreshold: 1, profile: "ranged" }] },
  ginyu: { id: "ginyu", name: "Capitão Ginyu", skin: "ginyu", hp: 1000, damage: 31, profile: "balanced", phases: [{ name: "Capitão da Força", hpThreshold: 1, profile: "balanced" }, { name: "Investida decisiva", hpThreshold: 0.38, profile: "aggressive" }] },
  frieza: { id: "frieza", name: "Freeza", skin: "frieza", hp: 1900, damage: 38, profile: "ranged", phases: [{ name: "Primeira forma", hpThreshold: 1, profile: "ranged" }, { name: "Segunda forma", hpThreshold: 0.78, profile: "tank" }, { name: "Terceira forma", hpThreshold: 0.56, profile: "speedster" }, { name: "Forma final", hpThreshold: 0.34, profile: "aggressive" }, { name: "Poder total", hpThreshold: 0.14, profile: "balanced" }] },
});

const snakeSteps = Array.from({ length: 25 }, (_, index) => ({
  id: "snake-" + (index + 1), type: "loreCheckpoint", checkpoint: index + 1,
  text: "Atravesse o Caminho da Serpente em ordem: marco " + (index + 1) + "/25.",
}));
const ballIds = Array.from({ length: 7 }, (_, i) => "namekBall" + (i + 1));
const BOSS_LANDMARKS = Object.freeze({cell:'cellArena',dabura:'babidiShip',kidBuu:'buuWastes',
  pilaf: "pilafHideout", jackieChun: "tournament", generalBlue: "ribbonCamp",
  commanderRed: "ribbonBase", grandpaGohan: "babaArena", tenshinhan: "tournament",
  tambourine: "demonCity", kingPiccolo: "piccoloKeep", piccoloJr: "tournament",
  raditz: "raditzCrater", nappa: "saiyanBattlefield", vegeta: "saiyanBattlefield",
  dodoria: "namekRidge", zarbon: "namekCamp", guldo: "ginyuField",
  recoome: "ginyuField", burter: "ginyuField", jeice: "ginyuField", ginyu: "ginyuField",
  frieza: "namekFinal",
});
const O = (id, type, text, extra = {}) => ({ id, type, text, ...extra });
const reach = (id, text, extra = {}) => O(id, "reach", text, extra);
const wave = (id, text, spawnAt, enemyName, skin, count, profile = "aggressive") => O(id, "defeatWave", text, { required: count, encounter: { kind: "wave", spawnAt, enemies: [{ name: enemyName, skin, count, profile }] } });
const boss = (id, text, bossId) => O(id, "boss", text, { bossId, encounter: { kind: "boss", bossId, spawnAt: BOSS_LANDMARKS[bossId] } });

const QUESTS = [
  { id: "db-paozu", saga: "dragon-ball", title: "Sinais nas Montanhas Paozu", description: "Uma viajante procura esferas antigas; rastros levam a um grupo que também as busca.", objectives: [reach("paozu", "Investigue as Montanhas Paozu.", { target: "paozu" }), O("meet-bulma", "talk", "Converse com Bulma no ponto de encontro.", { target: "bulma" }), O("pilaf-intel", "collect", "Recupere a pista deixada pela patrulha de Pilaf.", { target: "pilafNote1", item: "pilafIntel", count: 1 }), O("pilaf-scouts", "killCount", "Afaste a patrulha que procura a pista.", { required: 3, encounter: { kind: "wave", spawnAt: "pilafTrail", enemies: [{ name: "Batedor de Pilaf", skin: "soldier", count: 3, profile: "aggressive" }] } })], rewards: { xp: 150, zenni: 80 }, next: "db-pilaf" },
  { id: "db-pilaf", saga: "dragon-ball", title: "O esconderijo de Pilaf", description: "Siga as marcas até o esconderijo e interrompa a busca pelas esferas.", objectives: [reach("pilaf-hideout", "Localize o esconderijo de Pilaf.", { target: "pilafHideout" }), wave("hideout-guards", "Rompa a defesa do esconderijo.", "pilafHideout", "Guarda de Pilaf", "soldier", 4), boss("pilaf-automaton", "Derrote Pilaf e encerre a expedição.", "pilaf")], rewards: { xp: 190, zenni: 120, flags: ["pilaf_expedition_stopped"] }, next: "db-kame-training" },
  { id: "db-kame-training", saga: "dragon-ball", title: "Disciplina da Tartaruga", description: "Mestre Kame oferece um treino que prepara o guerreiro para o torneio.", objectives: [reach("kame-island", "Viaje até a Kame House.", { target: "kameHouse" }), O("meet-kame", "talk", "Peça orientação ao Mestre Kame.", { target: "kameHouse" }), O("learn-kame", "train", "Complete o treinamento de Kame para aprender sua técnica.", { loreId: "kame" })], rewards: { xp: 180, zenni: 90, techniques: ["kame"] }, next: "db-21st" },
  { id: "db-21st", saga: "dragon-ball", title: "21º Torneio de Artes Marciais", description: "Mostre sua técnica em uma sequência de lutas antes do encontro final.", objectives: [reach("21st-arena", "Chegue às Terras do Torneio.", { target: "tournament" }), wave("21st-qualifier", "Supere a luta classificatória.", "tournament", "Competidor do torneio", "turtle", 2, "technical"), wave("21st-semifinal", "Vença a luta intermediária.", "tournament", "Finalista do torneio", "tien", 1, "technical"), boss("jackie-final", "Enfrente Jackie Chun na final.", "jackieChun")], rewards: { xp: 220, zenni: 140 }, next: "db-ribbon-outposts" },
  { id: "db-ribbon-outposts", saga: "dragon-ball", title: "Rastros da Red Ribbon", description: "Investigue os postos da organização, reúna informações e enfrente seu oficial.", objectives: [reach("rr-front", "Entre no território da Red Ribbon.", { target: "ribbonFront" }), wave("rr-sentries", "Desative a patrulha de sentinelas.", "ribbonFront", "Sentinela Red Ribbon", "soldier", 3), O("rr-relay", "kill", "Desative o transmissor da patrulha.", { target: "rr-relay", encounter: { kind: "wave", spawnAt: "ribbonCamp", enemies: [{ name: "Operador da Red Ribbon", skin: "soldier", count: 1, profile: "technical" }] } }), O("rr-intelligence", "collect", "Reúna os três registros dos postos avançados.", { item: "redRibbonIntel", collectibles: ["rrIntel1", "rrIntel2", "rrIntel3"], count: 3 }), O("rr-reinforcements", "survive", "Resista à chegada dos reforços.", { seconds: 14, target: "ribbonCamp" }), boss("blue-duel", "Derrote o General Blue.", "generalBlue")], rewards: { xp: 260, zenni: 180 }, next: "db-ribbon-base" },
  { id: "db-ribbon-base", saga: "dragon-ball", title: "A base principal", description: "Use os registros para localizar o centro de comando da Red Ribbon.", objectives: [reach("rr-command", "Alcance a base principal.", { target: "ribbonBase" }), wave("rr-base-guard", "Supere as forças que protegem o comando.", "ribbonBase", "Guarda da Red Ribbon", "soldier", 4, "technical"), boss("red-command", "Enfrente o Comandante Red.", "commanderRed")], rewards: { xp: 250, zenni: 190, flags: ["red_ribbon_defeated"] }, next: "db-yamcha-baba" },
  { id: "db-yamcha-baba", saga: "dragon-ball", title: "O desafio do deserto", description: "Rastros no deserto levam a um teste de combate ligado à busca pelas esferas.", objectives: [reach("yamcha-territory", "Explore o Deserto de Yamcha.", { target: "yamchaDesert" }), wave("desert-bandits", "Afaste os bandidos do deserto.", "yamchaDesert", "Bandido do deserto", "yamcha", 3), O("baba-meet", "talk", "Procure orientação no ponto de encontro de Baba.", { target: "babaArena" }), boss("gohan-trial", "Supere o desafio de Gohan Ancião.", "grandpaGohan")], rewards: { xp: 210, zenni: 150 }, next: "db-22nd" },
  { id: "db-22nd", saga: "dragon-ball", title: "22º Torneio de Artes Marciais", description: "A nova competição exige leitura de ritmo, defesa e precisão.", objectives: [reach("22nd-arena", "Retorne às Terras do Torneio.", { target: "tournament" }), wave("22nd-qualifier", "Passe pela classificatória.", "tournament", "Competidor experiente", "tien", 2, "technical"), boss("tien-final", "Enfrente Tenshinhan na luta principal.", "tenshinhan")], rewards: { xp: 260, zenni: 190 }, next: "db-piccolo-daimaoh" },
  { id: "db-piccolo-daimaoh", saga: "dragon-ball", title: "A ameaça demoníaca", description: "Uma força hostil ataca os assentamentos; siga seus rastros até o líder.", objectives: [reach("demon-attack", "Investigue os relatos de ataques na cidade.", { target: "demonCity" }), wave("demon-wave", "Proteja a região dos guerreiros demoníacos.", "demonCity", "Guerreiro demoníaco", "demon", 4, "aggressive"), boss("tambourine-hunt", "Derrote Tambourine e descubra quem o enviou.", "tambourine"), O("king-piccolo-phase", "bossPhase", "Resista à mudança de ritmo de Piccolo Daimaoh.", { bossId: "kingPiccolo", phaseIndex: 1, encounter: { kind: "boss", bossId: "kingPiccolo", spawnAt: "piccoloKeep" } }), boss("king-piccolo-final", "Derrote Piccolo Daimaoh.", "kingPiccolo")], rewards: { xp: 330, zenni: 220 }, next: "db-23rd" },
  { id: "db-23rd", saga: "dragon-ball", title: "23º Torneio de Artes Marciais", description: "O último torneio desta era decide o rumo dos antigos rivais.", objectives: [reach("23rd-arena", "Chegue às Terras do Torneio.", { target: "tournament" }), wave("23rd-qualifier", "Conclua a sequência classificatória.", "tournament", "Competidor da final", "piccolo", 3, "technical"), O("piccolo-jr-phase", "bossPhase", "Acompanhe a escalada de poder de Piccolo Jr.", { bossId: "piccoloJr", phaseIndex: 1, encounter: { kind: "boss", bossId: "piccoloJr", spawnAt: "tournament" } }), boss("piccolo-jr-final", "Vença Piccolo Jr. e conclua a era dos torneios.", "piccoloJr")], rewards: { xp: 360, zenni: 260, flags: ["earth_dragonball_complete"] }, next: "saiyan-raditz" },
  { id: "saiyan-raditz", saga: "saiyan", title: "A cratera de Raditz", description: "Uma nave caiu nas montanhas; investigue a ameaça antes que ela alcance os povoados.", objectives: [reach("raditz-crater", "Localize a cratera da nave.", { target: "raditzCrater" }), O("raditz-signal", "interact", "Investigue os destroços da nave.", { target: "raditzCrater" }), O("raditz-phase", "bossPhase", "Raditz muda de tática quando pressionado.", { bossId: "raditz", phaseIndex: 1, encounter: { kind: "boss", bossId: "raditz", spawnAt: "raditzCrater" } }), boss("raditz-defeat", "Derrote Raditz.", "raditz")], rewards: { xp: 300, zenni: 200 }, next: "saiyan-kaio" },
  { id: "saiyan-kaio", saga: "saiyan", title: "Caminho da Serpente", description: "Após a queda, atravesse o Outro Mundo e treine com o Senhor Kaio.", objectives: [O("otherworld-route", "travel", "Chegue ao Outro Mundo para iniciar o percurso.", { target: "otherworld" }), O("snake-way", "sequence", "Atravesse todos os marcos do Caminho da Serpente.", { steps: snakeSteps }), O("bubbles-greeting", "loreBubbles", "Alcance Bubbles antes do treinamento.", { target: "bubbles" }), O("kaio-training", "train", "Conclua o treinamento existente do Senhor Kaio.", { loreId: "kaio" })], rewards: { xp: 280, zenni: 160, flags: ["kaio_training_complete"] }, next: "saiyan-invasion" },
  { id: "saiyan-invasion", saga: "saiyan", title: "A invasão Saiyajin", description: "Defenda a região, sobreviva à primeira onda e enfrente os invasores em sequência.", objectives: [reach("battlefield", "Alcance o campo de batalha.", { target: "saiyanBattlefield" }), wave("saibamen-wave", "Derrote os Saibamen.", "saiyanBattlefield", "Saibaman", "saibaman", 4), O("hold-line", "survive", "Mantenha a posição durante o próximo avanço.", { seconds: 12, target: "saiyanBattlefield" }), wave("nappa-guards", "Afaste a escolta de Nappa.", "saiyanBattlefield", "Soldado Saiyajin", "soldier", 2, "tank"), boss("nappa-duel", "Derrote Nappa.", "nappa"), O("vegeta-phase-two", "bossPhase", "Vegeta acelera a ofensiva.", { bossId: "vegeta", phaseIndex: 1, encounter: { kind: "boss", bossId: "vegeta", spawnAt: "saiyanBattlefield" } }), O("vegeta-phase-three", "bossPhase", "Resista à última ofensiva de Vegeta.", { bossId: "vegeta", phaseIndex: 2, encounter: { kind: "boss", bossId: "vegeta", spawnAt: "saiyanBattlefield" } }), boss("vegeta-final", "Derrote Vegeta e encerre a invasão.", "vegeta")], rewards: { xp: 520, zenni: 340, flags: ["saiyan_saga_complete"] }, next: "namek-journey" },
  { id: "namek-journey", saga: "saiyan", title: "Rota para Namekusei", description: "Marque Namek no atlas, alcance a órbita e faça a viagem pelo espaço.", objectives: [O("travel-namek", "travel", "Viaje da Terra até Namekusei usando a navegação espacial.", { target: "namek" })], rewards: { xp: 180, zenni: 120 }, next: "namek-arrival" },
  { id: "namek-arrival", saga: "namek", title: "Primeiros sinais em Namekusei", description: "Encontre uma aldeia e descubra como a força invasora está agindo.", objectives: [reach("namek-landing", "Explore a região de chegada.", { target: "namekLanding" }), O("namek-village-region", "visitRegion", "Localize a região da aldeia namekuseijin.", { target: "Vale do Patriarca" }), reach("namek-village", "Encontre a aldeia próxima ao vale.", { target: "namekVillage" }), wave("freeza-scouts", "Interrompa a patrulha que ameaça a aldeia.", "namekVillage", "Soldado de Freeza", "soldier", 3, "ranged"), O("namek-ally", "talk", "Converse com o aliado da aldeia.", { target: "namekVillage" })], rewards: { xp: 260, zenni: 180 }, next: "namek-dragon-balls" },
  { id: "namek-dragon-balls", saga: "namek", title: "As esferas de Namekusei", description: "Proteja as aldeias e reúna as sete esferas namekuseijins sem misturá-las às da Terra.", objectives: [reach("namek-villages", "Visite a região das aldeias.", { target: "namekCamp" }), wave("namek-invaders", "Afaste a força que ocupa o acampamento.", "namekCamp", "Invasor de Freeza", "soldier", 4, "ranged"), O("namek-balls", "collect", "Encontre as sete esferas de Namekusei.", { item: "namekDragonBall", collectibles: ballIds, count: 7 })], rewards: { xp: 340, zenni: 210, items: { namekDragonBalls: 7 } }, next: "namek-dodoria" },
  { id: "namek-dodoria", saga: "namek", title: "A perseguição de Dodoria", description: "Um comandante bruto caça sobreviventes e protege a operação de Freeza.", objectives: [reach("dodoria-ridge", "Siga os rastros até a crista ocupada.", { target: "namekRidge" }), boss("dodoria-duel", "Derrote Dodoria.", "dodoria")], rewards: { xp: 300, zenni: 210 }, next: "namek-zarbon" },
  { id: "namek-zarbon", saga: "namek", title: "A segunda forma de Zarbon", description: "Zarbon combate com precisão e libera um poder mais agressivo quando pressionado.", objectives: [reach("zarbon-camp", "Investigue o acampamento da Força Freeza.", { target: "namekCamp" }), O("zarbon-phase-two", "bossPhase", "Zarbon libera sua força oculta.", { bossId: "zarbon", phaseIndex: 1, encounter: { kind: "boss", bossId: "zarbon", spawnAt: "namekCamp" } }), boss("zarbon-defeat", "Derrote Zarbon.", "zarbon")], rewards: { xp: 360, zenni: 240 }, next: "namek-elder" },
  { id: "namek-elder", saga: "namek", title: "O Patriarca e Dende", description: "Encontre os namekuseijins que guardam a história das esferas e recupere forças.", objectives: [reach("elder-home", "Encontre o local do Patriarca.", { target: "namekElder" }), O("elder-counsel", "talk", "Peça orientação ao Patriarca.", { target: "namekElder" }), O("dende-aid", "interact", "Receba ajuda do aliado namekuseijin.", { target: "namekVillage" })], rewards: { xp: 240, zenni: 140, points: 2, flags: ["namek_potential_unlocked"], restore: true }, next: "namek-ginyu" },
  { id: "namek-ginyu", saga: "namek", title: "A Força Ginyu", description: "Enfrente o esquadrão em ordem; cada integrante traz um padrão de combate próprio.", objectives: [reach("ginyu-ground", "Alcance o campo onde o esquadrão se reuniu.", { target: "ginyuField" }), boss("guldo-duel", "Derrote Guldo, que ataca em breves aberturas.", "guldo"), boss("recoome-duel", "Supere a resistência e os golpes pesados de Recoome.", "recoome"), boss("burter-duel", "Acompanhe a velocidade de Burter.", "burter"), boss("jeice-duel", "Feche a distância contra os disparos de Jeice.", "jeice"), boss("ginyu-duel", "Enfrente o Capitão Ginyu.", "ginyu")], rewards: { xp: 620, zenni: 420, flags: ["ginyu_force_defeated"] }, next: "namek-frieza" },
  { id: "namek-frieza", saga: "namek", title: "O poder de Freeza", description: "A luta atravessa as formas e a escalada de poder do tirano; sobreviva a cada mudança de padrão.", objectives: [reach("frieza-ground", "Chegue à área do confronto final.", { target: "namekFinal" }), O("frieza-phase-two", "bossPhase", "Freeza revela sua segunda forma.", { bossId: "frieza", phaseIndex: 1, encounter: { kind: "boss", bossId: "frieza", spawnAt: "namekFinal" } }), O("frieza-phase-three", "bossPhase", "Freeza muda novamente sua forma e seus ataques.", { bossId: "frieza", phaseIndex: 2, encounter: { kind: "boss", bossId: "frieza", spawnAt: "namekFinal" } }), O("frieza-final-form", "bossPhase", "Enfrente a forma final de Freeza.", { bossId: "frieza", phaseIndex: 3, encounter: { kind: "boss", bossId: "frieza", spawnAt: "namekFinal" } }), O("frieza-full-power", "bossPhase", "Resista ao poder total de Freeza.", { bossId: "frieza", phaseIndex: 4, encounter: { kind: "boss", bossId: "frieza", spawnAt: "namekFinal" } }), boss("frieza-defeat", "Derrote Freeza.", "frieza")], rewards: { xp: 850, zenni: 600, flags: ["frieza_defeated"] }, next: "namek-escape" },
  { id: "namek-escape", saga: "namek", title: "Fuga de Namekusei", description: "A superfície está instável. Alcance o ponto de fuga e entre em órbita para concluir a jornada.", objectives: [O("escape-survive", "survive", "Sobreviva ao caos e prepare a saída.", { seconds: 10, target: "namekEscape" }), O("escape-point", "returnTo", "Volte ao ponto de fuga na superfície.", { target: "namekEscape" }), O("leave-namek", "travel", "Abandone a superfície e alcance o espaço.", { target: "space", from: "namek" })], rewards: { xp: 500, zenni: 350, flags: ["namek_saga_complete"] }, next: 'android-warning' },
  {id:'android-warning',saga:'androids',title:'O aviso do futuro',description:'Investigue os sinais de uma nova ameaça e prepare a defesa da cidade.',objectives:[O('return-earth','travel','Retorne à Terra.',{target:'earth'}),reach('lab','Procure o laboratório da Capsule Corp.',{target:'capsuleLab'}),O('briefing','talk','Ouça o plano de Bulma.',{target:'capsuleLab'})],rewards:{xp:450,zenni:280},next:'android-siege'},
  {id:'android-siege',saga:'androids',title:'Ruas sob cerco',description:'Abra uma passagem para a evacuação e destrua a força de ocupação.',objectives:[reach('city','Chegue ao distrito ameaçado.',{target:'androidTown'}),wave('android-scouts','Elimine as unidades de reconhecimento.','androidTown','Androide batedor','android',3,'speedster'),O('evacuation','survive','Segure a posição de evacuação por 20 segundos.',{seconds:20,target:'androidTown'}),wave('android-artillery','Neutralize os atiradores de supressão.','androidTown','Androide de supressão','android',3,'ranged'),O('report','talk','Confirme a evacuação com Bulma.',{target:'capsuleLab'})],rewards:{xp:600,zenni:380},next:'cell-games'},
  {id:'cell-games',saga:'androids',title:'O desafio de Cell',description:'Uma arena exposta, três ritmos de combate e nenhuma vitória sem leitura.',objectives:[reach('arena','Encontre a arena de Cell.',{target:'cellArena'}),O('cell-phase','bossPhase','Force Cell a revelar sua última ofensiva.',{bossId:'cell',phaseIndex:2,encounter:{kind:'boss',bossId:'cell',spawnAt:'cellArena'}}),boss('cell-final','Derrote Cell.','cell'),O('home','returnTo','Retorne ao laboratório para encerrar a crise.',{target:'capsuleLab'})],rewards:{xp:1000,zenni:650,points:3,flags:['cell_saga_complete']},next:'buu-signal'},
  {id:'buu-signal',saga:'buu',title:'Energia nas profundezas',description:'Siga o desvio de energia até a nave enterrada no deserto.',objectives:[O('buu-brief','talk','Investigue a leitura anormal de energia.',{target:'capsuleLab'}),reach('ship','Localize a nave de Babidi.',{target:'babidiShip'}),wave('ship-guards','Abra passagem pela guarda da nave.','babidiShip','Guarda de Babidi','demon',4,'tank'),boss('dabura-final','Supere Dabura.','dabura')],rewards:{xp:750,zenni:450},next:'buu-last-stand'},
  {id:'buu-last-stand',saga:'buu',title:'A última resistência',description:'Leve o confronto para longe das cidades e encontre a abertura na tempestade de ki.',objectives:[O('sacred-travel','travel','Viaje ao Mundo dos Kaioshins.',{target:'sacred'}),reach('wastes','Chegue à planície do confronto.',{target:'buuWastes'}),O('buu-phase','bossPhase','Resista às três fases de Majin Buu.',{bossId:'kidBuu',phaseIndex:2,encounter:{kind:'boss',bossId:'kidBuu',spawnAt:'buuWastes'}}),boss('buu-final','Derrote Majin Buu.','kidBuu')],rewards:{xp:1300,zenni:800,points:4,flags:['buu_saga_complete']},next:'earth-epilogue'},
  {id:'earth-epilogue',saga:'buu',title:'Um mundo para reconstruir',description:'A campanha termina; a vida no mundo continua com exploração, ofícios e projetos coletivos.',objectives:[O('earth-home','travel','Volte à Terra.',{target:'earth'}),O('kame-epilogue','talk','Converse com Mestre Kame sobre seu próximo caminho.',{target:'kameHouse',reply:'Mestre Kame: Salvar o mundo é só o começo. Cuide dele. Encontre um lugar, ajude alguém e continue treinando.'})],rewards:{xp:450,zenni:400,restore:true},next:null},
];

const QUEST_BY_ID = new Map(QUESTS.map((q) => [q.id, q]));
const LANDMARK_BY_ID = new Map(Object.values(LANDMARKS).map((l) => [l.id, l]));
const COLLECTIBLE_IDS = new Set(Object.values(LANDMARKS).filter((l) => l.item).map((l) => l.id));

return { SAGAS, LANDMARKS, LANDMARK_BY_ID, ENEMY_PROFILES, BOSSES, BOSS_LANDMARKS, QUESTS, QUEST_BY_ID, COLLECTIBLE_IDS };
});
