const fs=require('fs');const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
edit('public/beta-ui.js',s=>s.replace('background-paozu.png','paozu-background.jpg').replace("const launch=btn('✦ Central','',","const launch=btn('✦ Central',()=>{},"));
edit('public/app.js',s=>s.replace('  function join(resume) {',"  const betaInvite=()=>{try{return sessionStorage.getItem('uz-invite')||'';}catch{return '';}};\n  function join(resume) {").replace('{ token: savedToken }','{ token: savedToken,invite:betaInvite() }').replace('{ name: $("player-name").value.trim(), origin: selected, creation:', '{ invite:betaInvite(),name: $("player-name").value.trim(), origin: selected, creation:').replace('  document.addEventListener("beta-open",()=>resetInput());\n',''));
edit('src/security.js',s=>s.replace("const now=Date.now();let e=this.entries.get(key);","const now=Date.now();if(!this.entries.has(key)&&this.entries.size>=10000){for(const[k,v]of this.entries)if(v.until<now)this.entries.delete(k);if(this.entries.size>=10000)return false;}let e=this.entries.get(key);"));
edit('src/store.js',s=>s.replace(' async init(){',` async acquire(){await fs.mkdir(this.directory,{recursive:true});const lock=path.join(this.directory,'server.lock');try{this.lock=await fs.open(lock,'wx',0o600);await this.lock.writeFile(JSON.stringify({pid:process.pid,startedAt:Date.now()}));}catch(e){if(e.code==='EEXIST')throw Error('Há um server.lock neste diretório. Encerre a instância anterior ou verifique o PID antes de remover um lock obsoleto.');throw e;}}
 async release(){if(this.lock){await this.lock.close();this.lock=null;await fs.unlink(path.join(this.directory,'server.lock'));}}
 async init(){`));
edit('server.js',s=>s.replace('  await store.init();\n  await store.loadWorld();','  await store.acquire();\n  try{await store.init();await store.loadWorld();}catch(e){await store.release();throw e;}').replace("if(data.action==='restore'&&!token){const recovered=store.recover(data.code);","if(data.action==='restore'&&!token){capture();const recovered=store.recover(data.code);").replace("connections.set(ip,Math.max(0,(connections.get(ip)||1)-1));","const left=(connections.get(ip)||1)-1;if(left>0)connections.set(ip,left);else connections.delete(ip);").replace('        store\n          .flush()','        persist()').replace('  await new Promise((resolve) =>\n    server.listen(options.port ?? process.env.PORT ?? 3000, "0.0.0.0", resolve),\n  );',`  try{await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(options.port??process.env.PORT??3000,options.host||process.env.HOST||(cfg.production?'127.0.0.1':'0.0.0.0'),resolve);});}catch(e){clearInterval(loop);clearInterval(save);await store.release();throw e;}`).replace('    await store.flush();\n  };','    try{await store.flush();}finally{await store.release();}\n  };'));
edit('src/engine.js',s=>s.replace('      originX: p.x,','      mode:p.mode,\n      originX: p.x,').replaceAll('mode:owner.mode','mode:s.mode').replace('this.reward(p, target.rewardXP || (target.boss ? 100 : 28));','this.reward(p, target.rewardXP ?? (target.boss ? 100 : 28));'));
// Unique active encounter cap avoids persistent enemy accumulation under mass exploration.
edit('src/open-world.js',s=>s.replace('if(this.explorationCells.has(key))','if(this.enemies.length>=2400)continue;\n        if(this.explorationCells.has(key))'));
// Update manifests consistently without installing dependencies.
const pkg=JSON.parse(fs.readFileSync('package.json'));pkg.version='1.0.0-beta.1';pkg.description='Universe Z: beta de RPG sandbox multiplayer';pkg.scripts['test:beta']='node --test tests/beta.test.js';pkg.scripts['check:beta']='node tools/check-beta.cjs';pkg.scripts['test:load']='node tools/load-beta.cjs';pkg.scripts['ops']='node tools/beta-ops.cjs';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n');if(fs.existsSync('package-lock.json')){const lock=JSON.parse(fs.readFileSync('package-lock.json'));lock.version=pkg.version;if(lock.packages?.[''])lock.packages[''].version=pkg.version;fs.writeFileSync('package-lock.json',JSON.stringify(lock,null,2)+'\n');}
console.log('Security lifecycle and UX consistency corrected.');
