const fs=require('fs');const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
edit('public/index.html',s=>s.replace('<script src="/illustrated-ui.js','<script src="/portraits.js"></script>\n    <script src="/illustrated-ui.js').replace('</head>','<link rel="stylesheet" href="/frontiers.css">\n  </head>'));
edit('public/illustrated-ui.js',s=>s.replace('im.src = asset("combat", origins[id] || 22);','im.src = UZPortrait.origin(id) || asset("combat", origins[id] || 22);').replace('b.prepend(picture("combat", origins[b.dataset.origin] || 22));',`{const icon=new Image();icon.alt='';icon.src=UZPortrait.origin(b.dataset.origin);b.prepend(icon);}`).replace('node.prepend(im);\n    },\n    panel(type)',"im.src=UZPortrait.origin(origin)||im.src;\n      node.prepend(im);\n    },\n    panel(type)"));
edit('public/app.js',s=>s.replace('let state = null,','let seenDialogue=null;\n  let state = null,').replace('const c = canvas.getContext("2d");\n    c.clearRect','if(window.UZPortrait?.canvas(canvas,skin))return;\n    const c = canvas.getContext("2d");\n    c.clearRect').replace('const p = state.self;\n    if (lastWorld',`const p = state.self;
    if(p.dialogue&&p.dialogue.id!==seenDialogue&&!scene&&!$('panel').open&&!document.getElementById('sandbox-panel')?.open){seenDialogue=p.dialogue.id;playScene([p.dialogue]);}
    if (lastWorld`).replace('(enemy.boss ? "CHEFE" : "ALVO")','(enemy.boss ? "CHEFE" : enemy.rank==="elite"?"ELITE":enemy.rank==="veteran"?"VETERANO":"ALVO")').replace('combatHints[enemy.pattern] || "Observe a postura e mantenha sua distância."',`enemy.state==='recover'?'ABERTURA · ataque agora para causar +20% de dano.':enemy.state==='guard'?'GUARDA · flanqueie ou segure Golpe para quebrá-la.':combatHints[enemy.pattern] || "Observe a postura e mantenha sua distância."`).replace('    c.fillStyle = "#172b2740";',`    window.UZPortrait?.draw(c,frame.skin,460,20,540,540);
    c.fillStyle = "#172b2740";`).replace('  function intro() {',"  window.addEventListener('portrait-ready',()=>{if(scene)drawScene();});\n  function intro() {").replace('Siga o radar até os pontos vermelhos. Toque Golpe para encadear três ataques; o último afasta o inimigo.','Golpe encadeia três ataques. Após o terceiro, Esquiva persegue o alvo lançado por 22 ki. Segure Golpe para quebrar a guarda.').replace('Uma defesa no tempo certo abre o contra-ataque.','Defenda no instante do impacto para contra-atacar. Ataque na recuperação do inimigo para causar mais dano.'));
edit('public/creator.js',s=>s.replace("stage.append(canvas,race,note)","const lineage=new Image();lineage.className='creator-lineage';lineage.alt='Retrato ilustrado da origem';stage.append(lineage,canvas,race,note)").replace("function render(){controls.replaceChildren();","function render(){lineage.src=UZPortrait.origin(origin);controls.replaceChildren();").replace("'A aparência acompanha seu personagem no mundo.'","'Retrato da origem e prévia da sua aparência no mundo.'").replace("x:180,y:290,state:'idle'},clock,1.7","x:180,y:290,state:'idle'},clock,2.2"));
// Unique deterministic visual rhythm and semantic effects for every furnished prop.
edit('public/world-kit.js',s=>s.replace("if(o.kind==='prop')return sprite(c,'furniture',o.sprite,o.x,o.y,o.size);",`if(o.kind==='prop'){
 const index=o.sprite,row=Math.floor(index/14),phase=h%628/100,rate=.7+(index%11)*.09;
 if(row===4||[165,167,177,188,194].includes(index))glow(c,o.x,o.y-o.size*.35,o.size*.6,'#75e6ff25');
 if(row===6||row===11){c.save();c.strokeStyle='#82eaff70';c.lineWidth=1;c.beginPath();c.arc(o.x,o.y-o.size*.4,5+Math.sin(clock*rate+phase)*2,0,TAU);c.stroke();c.restore();}
 if(row===7||row===8||row===13){c.fillStyle=row===13?'#edce8a99':'#b2f2b080';for(let i=0;i<2;i++){const p=clock*rate+phase+i*2;c.beginPath();c.arc(o.x+Math.sin(p)*20,o.y-25-((clock*9+index*3+i*18)%42),1.2,0,TAU);c.fill();}}
 return sprite(c,'furniture',index,o.x,o.y,o.size,row===7?Math.sin(clock*rate+phase)*.018:0);
 }`));
console.log('Illustrated avatars, dialogue scenes and living props integrated.');
